linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental

issues:
  exclude-files:
    - swagger.go
    - _test.go
  exclude-rules:
    - text: "not declared by package utf8"
      linters:
        - typecheck
    - text: "unicode/utf8/utf8.go"
      linters:
        - typecheck
    - path: _test.go
      linters:
        - funlen
    - path: swagger.go
      linters:
        - unused
        - gofmt

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - govet
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - nakedret
    - prealloc
    - copyloopvar
    - gocritic
    - bodyclose
    - stylecheck
    - gosec
    - revive
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - goimports
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gochecknoinits
    - funlen