// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gin-gonic/gin"
	"github.com/rahul-aut-ind/service-user/domain/logger"
	"github.com/rahul-aut-ind/service-user/infrastructure/routes"
	"github.com/rahul-aut-ind/service-user/interfaceadapters/controllers/usercontroller"
	"github.com/rahul-aut-ind/service-user/interfaceadapters/handlers/requesthandler"
	"github.com/rahul-aut-ind/service-user/interfaceadapters/repositories/userrepo"
	"github.com/rahul-aut-ind/service-user/internal/config"
	"github.com/rahul-aut-ind/service-user/services/userservice"
)

// Injectors from wire.go:

func New(e *gin.Engine) (*App, error) {
	requestHandler := requesthandler.New(e)
	loggerLogger := logger.New()
	env := config.NewEnv()
	mysqlRepository := userrepo.New(loggerLogger, env)
	service := userservice.New(mysqlRepository, loggerLogger)
	controller := usercontroller.New(service, loggerLogger)
	routesRoutes := routes.New(requestHandler, controller)
	app := newApp(routesRoutes, env, loggerLogger, e)
	return app, nil
}
